config/routes.rb
Rails.application.routes.draw do
  root :to =>'top#index'

  resources :tweets do
      collection do
          post :confirm
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :destroy]

  def confirm
    @tweet = Tweet.new(tweet_params)
    render :new if @tweet.invalid?
  end

  def show
  end

  def index
    @tweets = Tweet.all
  end

  def new
    if params[:back]
      @tweet = Tweet.new(tweet_params)
    else
      @tweet = Tweet.new
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice:"ブログを削除しました！"
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice: "ブログを作成しました！"
    else
      render 'new'
    end
  end

  private
    def tweet_params
      params.require(:tweet).permit(:content)
    end

    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
      if action_name == 'new' || action_name == 'confirm'
          confirm_tweets_path

      elsif action_name == 'edit'
          tweet_path

      end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">TwitterClone</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">TwitterClone</a>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><a href="/">HOME</a></li>
              <li><a href="/tweets">つぶやき一覧</a></li>
              <li><a href="/tweets/new">新規投稿</a></li>
            </ul>
          </div>
        </div>
      </nav>


    <%= yield %>

    <footer>
      <p>2018年3月期生</p>
      <p>小山田湧亮</p>
    </footer>
  </body>
</html>

app/views/top/index.html.erb
<section class="main-header">
  <img src="/images/twitterClone.png">
</section>

<section class="about">
  <h1>About TwitterClone</h1>
  <p>
    TwitterCloneは、Twitterを真似たつぶやきアプリです。<br>
  </p>
  <p>
    思い思いのつぶやきができます。
  </p>
</section>
<section class="function">
  <h1>Function</h1>
  <div class="row">
    <div class="col-sm-12 col-md-3">
      <img src="/images/key.png">
      <p>ログイン機能</p>
      <p class="incomplete">未実装</p>
    </div>
    <div class="col-sm-12 col-md-3">
      <img src="/images/mails.png">
      <p>メール送信機能</p>
      <p class="incomplete">未実装</p>
    </div>
    <div class="col-sm-12 col-md-3">
      <img src="/images/girls.png">
      <p>友達つながり機能</p>
      <p class="incomplete">未実装</p>
    </div>
    <div class="col-sm-12 col-md-3">
      <img src="/images/comment.png">
      <p>コメント投稿機能</p>
      <p class="incomplete">未実装</p>
    </div>
  </div>
</section>

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: true, url: choose_new_or_edit) do |form| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-warning" role="alert"><%= @tweet.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
          <li class="alert alert-warning" role="alert"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="tweet_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "つぶやき一覧画面にもどる", tweets_path %>

app/views/tweets/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @tweet, url: tweets_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @tweet.content %></p>
  <%= form.submit  "投稿する" %>
<% end %>

<%= form_with(model: @tweet, url: new_tweet_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/tweets/edit.html.erb
<h1>つぶやきを編集する</h1>

<%= render 'form' %>

app/views/tweets/index.html.erb
<h1>つぶやき一覧</h1>

<p><%= notice %></p>

<table>

<% @tweets.each do |tweet| %>
  <tr>
    <td class="index_tweet_content"><%= tweet.content %></td>
    <td class="index_tweet_content"><%= link_to '編集', edit_tweet_path(tweet.id), class: 'btn btn-warning' %></td>
    <td class="index_tweet_content"><%= link_to '削除', tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>
<br>
<%= link_to '新しくつぶやきを投稿する', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>つぶやきを投稿する</h1>

<p><%= notice %></p>

<%= render 'form' %>